name: Bug 报告
description: 提交一个项目存在的 Bug 以帮助我们改进
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您提交 Bug 报告！请详细填写以下信息，这将帮助我们更快地定位和解决问题。

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 请简要描述您遇到的问题
      placeholder: 描述具体的问题现象...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 复现步骤
      description: 请详细描述重现该问题的步骤
      placeholder: |
        1. 打开...
        2. 点击...
        3. 输入...
        4. 观察到...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期结果
      description: 请描述您预期的结果
      placeholder: 描述应该发生什么...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 实际结果
      description: 请描述实际发生的结果
      placeholder: 描述实际发生了什么...
    validations:
      required: true

  - type: textarea
    id: screenshots-logs
    attributes:
      label: 截图或日志
      description: 请附上相关截图或日志以帮助我们定位问题
      placeholder: 可以粘贴截图或拖拽文件到这里...
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: 操作系统
      description: 您使用的操作系统和版本
      placeholder: 例如：Windows 11, macOS 14.0, Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: software-version
    attributes:
      label: 软件版本
      description: 浏览器或软件版本（如适用）
      placeholder: 例如：v0.0.1
    validations:
      required: false

  - type: input
    id: hardware
    attributes:
      label: 相关硬件
      description: 如果与硬件相关，请提供硬件信息
      placeholder: 例如：USB设备型号、制造商等
    validations:
      required: false

  - type: input
    id: project-version
    attributes:
      label: 项目版本
      description: 项目版本或提交哈希
      placeholder: 例如：v0.0.1 或 commit hash
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: 其他补充信息
      description: 如有其他补充说明，请在此提供
      placeholder: 其他相关信息...
    validations:
      required: false
